Task #5 - MVC Sales/SalesMVCApplication/Sales.MVCClient/Controllers/PriceHistoryController.cs
using Sales.BL.Interfaces;
using Sales.MVCClient.Helper;
using Sales.MVCClient.Models;
using Sales.MVCClient.Models.CreateEdit;
using Sales.MVCClient.Models.Pagination;
using Sales.MVCClient.Models.Visualization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sales.BL.Infrastructure;

namespace Sales.MVCClient.Controllers
{
    [Authorize(Roles = Sales.MVCClient.Helper.MagicString.RolesUser)]
    public class PriceHistoryController : Controller
    {
        Sales.BL.Handler handler;
        IPriceHistoryCRUD priceHistoryCRUD;
        MVCMapper mapper;
        const int pageSize = 3;

        public PriceHistoryController(IPriceHistoryCRUD phCRUD)
        {
            handler = new BL.Handler();
            handler.Connect(Sales.MVCClient.Helper.MagicString.PathSalesDataBase);
            priceHistoryCRUD = phCRUD;
            mapper = new MVCMapper();
        }

        // GET: PriceHistory
        public ActionResult Index(int pageNumber = 1)
        {
            if (User.IsInRole(Sales.MVCClient.Helper.MagicString.RolesAdmin))
                ViewBag.IsAdmin = true;
            else
                ViewBag.IsAdmin = false; 
            try
            {
                PageInfo pageInfo = new PageInfo
                {
                    PageNumber = pageNumber,
                    PageSize = pageSize,
                    TotalItems = priceHistoryCRUD.PriceHistories.Count()
                };
                IndexViewModelPagination ivmp = new IndexViewModelPagination
                {
                    PageInfo = pageInfo,
                    PriceHistoriesPerPages = priceHistoryCRUD.GetPriceHistoryPerPage(pageSize, pageNumber).Select(x => mapper.Mapping(x))
                };
                return View(ivmp);
            }
            catch (MyInvalidOperationException e)
            {
                ViewBag.Title = "Invalid Operation";
                ViewBag.ErrorMessage = e.ErrorMessage;
                return View("Error");
            }
            catch (Exception e)
            {
                if (User.IsInRole(Sales.MVCClient.Helper.MagicString.RolesAdmin))
                    ViewBag.ErrorMessage = new ErrorMessage().Get(e);
                return View("Error");
            }
        }

        // GET: PriceHistory/Details/5
        public ActionResult Details(int id)
        {
            var priceHistory = priceHistoryCRUD.PriceHistories.FirstOrDefault(x => x.ID == id);
            if (priceHistory != null)
                return View(mapper.Mapping(priceHistory));
            else
                return View("Error");
        }

        // GET: PriceHistory/Edit/5
        [Authorize(Roles = Sales.MVCClient.Helper.MagicString.RolesAdmin)]
        public ActionResult Edit(int id)
        {
            var priceHistory = priceHistoryCRUD.PriceHistories.FirstOrDefault(x => x.ID == id);
            if (priceHistory != null)
            {
                PriceHistoryCreateEdit price = new PriceHistoryCreateEdit()
                {
                    PriceHistory = mapper.Mapping(priceHistory),
                    Products = GetProductsSelectList()
                };
                return View(price);
            }
            else
                return View("Error");
        }

        // POST: PriceHistory/Edit/5
        [HttpPost]
        [Authorize(Roles = Sales.MVCClient.Helper.MagicString.RolesAdmin)]
        public ActionResult Edit(int id, PriceHistory priceHistory)
        {
            if (ModelState.IsValid == true)
                try
                {
                    priceHistoryCRUD.EditPriceHistory(mapper.Mapping(priceHistory));
                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    ViewBag.ErrorMessage = new ErrorMessage().Get(e);
                    return View("Error");
                }
            else
                return View(priceHistory);
        }

        // GET: PriceHistory/Delete/5
        [Authorize(Roles = Sales.MVCClient.Helper.MagicString.RolesAdmin)]
        public ActionResult Delete(int id)
        {
            var priceHistory = priceHistoryCRUD.PriceHistories.FirstOrDefault(x => x.ID == id);
            if (priceHistory != null)
                return View(mapper.Mapping(priceHistory));
            else
                return View("Error");
        }

        // POST: PriceHistory/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = Sales.MVCClient.Helper.MagicString.RolesAdmin)]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                priceHistoryCRUD.DeletePriceHistory(id);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage = new ErrorMessage().Get(e);
                return View("Error");
            }
        }

        public ActionResult Chart()
        {
            ViewBag.Products = new SelectList(handler.Products.Select(x => mapper.Mapping(x)), "ID", "Name");
            return View(new Product());
        }

        private SelectList GetProductsSelectList()
        {
            return new SelectList(handler.Products.Select(x => mapper.Mapping(x)), "ID", "Name");
        }

        public JsonResult GetChartData(string id)
        {
            int productId;
            if (Int32.TryParse(id.ToString(), out productId))
            {
                var result = priceHistoryCRUD.PriceHistories
                    .Where(x => x.Product_ID == productId)
                    .Select(x => new PriceHistoryChartItem() { Date = x.Date.ToShortDateString(), Price = x.Price });

                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
                return null;
        }
    }
}

Task #5 - MVC Sales/SalesMVCApplication/Sales.MVCClient/Views/PriceHistory/Chart.cshtml
@model Sales.MVCClient.Models.Product
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load('current', { 'packages': ['corechart'] })
    </script>
</head>

<h2>Chart</h2>

@{
    ViewBag.Title = "Home Page";
}

<form method="get">
    @Html.DropDownList("productId", ViewBag.Products as SelectList, string.Empty, new { htmlAttributes = new { @class = "form-control" } })

    <button type="button" onclick="drawChart()">Show</button>
</form>


<body>
    <section id="chart_divSection">
        <div id="chart_div"></div>
    </section>

    <script type="text/javascript">
        var e = document.getElementById("productId");

        function drawChart() {
            var options = {
                title: 'Price history',
                hAxis: { title: 'Date', titleTextStyle: { color: '#333' } },
                pointSize: 5,
            };

            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Date');
            data.addColumn('number', 'Price');

            $.getJSON('@Url.Action("GetChartData", "PriceHistory")', { id: e.value },
            function (result) {
                if (result.length) {
                    $.each(result, function (index, r) {
                        data.addRow(
                            [r.Date, r.Price]
                        );
                    });
                    var chart = new google.visualization.AreaChart(
                                    document.getElementById('chart_div'));
                    chart.draw(data, options);
                };
            });
        }
    </script>
</body>

Task #5 - MVC Sales/SalesMVCApplication/Sales.MVCClient/Views/PriceHistory/Delete.cshtml
@model Sales.MVCClient.Models.PriceHistory

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Manager</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.Date)</dt>
        <dd>@Html.DisplayFor(model => model.Date)</dd>

        <dt>@Html.DisplayNameFor(model => model.Product.Name)</dt>
        <dd>@Html.DisplayFor(model => model.Product.Name)</dd>

        <dt>@Html.DisplayNameFor(model => model.Price)</dt>
        <dd>@Html.DisplayFor(model => model.Price)</dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Task #5 - MVC Sales/SalesMVCApplication/Sales.MVCClient/Views/PriceHistory/Details.cshtml
@model Sales.MVCClient.Models.PriceHistory

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>PriceHistory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.Date)</dt>
        <dd>@Html.DisplayFor(model => model.Date)</dd>

        <dt>@Html.DisplayNameFor(model => model.Product.Name)</dt>
        <dd>@Html.DisplayFor(model => model.Product.Name)</dd>

        <dt>@Html.DisplayNameFor(model => model.Price)</dt>
        <dd>@Html.DisplayFor(model => model.Price)</dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Task #5 - MVC Sales/SalesMVCApplication/Sales.MVCClient/Views/PriceHistory/Edit.cshtml
@model Sales.MVCClient.Models.CreateEdit.PriceHistoryCreateEdit

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PriceHistory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PriceHistory.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.PriceHistory.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PriceHistory.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PriceHistory.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PriceHistory.Product_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.PriceHistory.Product_ID, Model.Products, string.Empty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PriceHistory.Product_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PriceHistory.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PriceHistory.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PriceHistory.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Task #5 - MVC Sales/SalesMVCApplication/Sales.MVCClient/Views/PriceHistory/Index.cshtml
@model Sales.MVCClient.Models.Pagination.IndexViewModelPagination
@using Sales.MVCClient.Helper
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

@{
    ViewBag.Title = "Home Page";
}
<table class="table">
    <tr>
        <td>@Html.DisplayNameFor(m => m.PriceHistoryForLabel.Date)</td>
        <td>@Html.DisplayNameFor(m => m.PriceHistoryForLabel.Product.Name)</td>
        <td>@Html.DisplayNameFor(m => m.PriceHistoryForLabel.Price)</td>
        <td>@MagicString.DisplayOperationLabel</td>
    </tr>
    @foreach (var item in Model.PriceHistoriesPerPages)
    {
        <tr>
            <td>@item.Date</td>
            <td>@item.Product.Name</td>
            <td>@item.Price</td>
            @if (ViewBag.IsAdmin)
            {
                <td>
                    @Html.ActionLink(MagicString.DisplayOperationLabelEdit, "Edit", new { id = item.ID }) |
                    @Html.ActionLink(MagicString.DisplayOperationLabelDetails, "Details", new { id = item.ID }) |
                    @Html.ActionLink(MagicString.DisplayOperationLabelDelete, "Delete", new { id = item.ID })
                </td>
            }
            else
            {
                <td>
                    @Html.ActionLink(MagicString.DisplayOperationLabelDetails, "Details", new { id = item.ID })
                </td>
            }
    </tr>
    }
</table>
<br />


<div class="btn-group">
    @Html.PageLinks(Model.PageInfo, x => Url.Action("Index", new { pageNumber = x }))
</div>